import './globals.css'
import { Inter } from 'next/font/google'
import icon from "../../public/assets/images/LogoLCA.png"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porfolio - Leonel Castañeda',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="conoceme">
       <link rel = "shortcut icon" href = "/favicon.png" type = "image/png"></link>
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}
