import './globals.css'
import { Inter } from 'next/font/google'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import {useLocale} from 'next-intl';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Porfolio - Leonel Castañeda',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return [{locale: 'es'}, {locale: 'en'}];
}

export default async function RootLayout({ children, params: {locale} }) {
  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={locale} id="conoceme" className=''>
       <link rel = "shortcut icon" href = "/favicon.png" type = "image/png"></link>
      <body className={`${inter.className} bg-white dark:bg-black`}>
        <NextIntlClientProvider locale={locale} messages={messages}>

        {children}</NextIntlClientProvider></body>
    </html>
  )
}
